apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - app-configmap.yaml
  - postgres-init-configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - pgbouncer-service.yaml
  - pgbouncer-deployment.yaml
  - app-service.yaml
  - app-deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ledger
      app.kubernetes.io/managed-by: kustomize
